controller_manager:
  ros__parameters:
    update_rate: 1000 #Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_group_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 100

joint_group_trajectory_controller:
  ros__parameters:
    use_sim_time: True
    joints:
      - thigh_joint_fr
      - leg_joint_fr
      - thigh_joint_fl
      - leg_joint_fl
      - thigh_joint_rr
      - leg_joint_rr
      - thigh_joint_rl
      - leg_joint_rl

    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity

    gains:
      thigh_joint_fr : {p: 100.0, d: 0.2, i: 0.0, i_clamp: 1.0, ff_velocity_scale: 1.0}
      leg_joint_fr : {p: 100.0, d: 0.2, i: 0.0, i_clamp: 1.0, ff_velocity_scale: 1.0}
      thigh_joint_fl : {p: 100.0, d: 0.2, i: 0.0, i_clamp: 1.0, ff_velocity_scale: 1.0}
      leg_joint_fl : {p: 100.0, d: 0.2, i: 0.0, i_clamp: 1.0, ff_velocity_scale: 1.0}
      thigh_joint_rr : {p: 100.0, d: 0.2, i: 0.0, i_clamp: 1.0, ff_velocity_scale: 1.0}
      leg_joint_rr : {p: 100.0, d: 0.2, i: 0.0, i_clamp: 1.0, ff_velocity_scale: 1.0}
      thigh_joint_rl : {p: 100.0, d: 0.2, i: 0.0, i_clamp: 1.0, ff_velocity_scale: 1.0}
      leg_joint_rl : {p: 100.0, d: 0.2, i: 0.0, i_clamp: 1.0, ff_velocity_scale: 1.0}

    # velocity_ff:
    #   thigh_joint_fr: 1.0
    #   leg_joint_fr: 1.0
    #   thigh_joint_fl: 1.0
    #   leg_joint_fl: 1.0
    #   thigh_joint_rr: 1.0
    #   leg_joint_rr: 1.0
    #   thigh_joint_rl: 1.0
    #   leg_joint_rl: 1.0

    state_publish_rate: 100.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    # constraints:
    #   stopped_velocity_tolerance: 0.01
    #   goal_time: 0.0
    #   thigh_joint_fr: {trajectory: 0.05, goal: 0.02}
    #   leg_joint_fr: {trajectory: 0.05, goal: 0.02}
    #   thigh_joint_fl: {trajectory: 0.05, goal: 0.02}
    #   leg_joint_fl: {trajectory: 0.05, goal: 0.02}
    #   thigh_joint_rr: {trajectory: 0.05, goal: 0.02}
    #   leg_joint_rr: {trajectory: 0.05, goal: 0.02}
    #   thigh_joint_rl: {trajectory: 0.05, goal: 0.02}
    #   leg_joint_rl: {trajectory: 0.05, goal: 0.02}