<?xml version="1.0"?>
<!--  
*****************************************************************************************
*
*  Filename:			quad.xacro
*  Created:				22/12/2023
*  Last Modified:	22/12/2023
*  Author:				Archit Jain
*  
*****************************************************************************************
-->
<robot name="quad" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find quad_description)/models/quad/quad_gazebo.xacro" />

  <!-- ****************** BASIC INERTIAL MACROS ***************************  -->
  <!-- Define intertial property macros  -->
  <xacro:macro name="box_inertia" params="m w h d *origin">
    <inertial>
      <xacro:insert_block name="origin"/>
      <mass value="${m}"/>
      <inertia  ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" 
                iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" 
                izz="${(m/12) * (w*w + h*h)}"/>
    </inertial>
  </xacro:macro>
  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0" iyy="${(m/12) * (3*r*r + h*h)}" iyz = "0" izz="${(m/2) * (r*r)}"/>
    </inertial>
  </xacro:macro>
  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0" iyy="${(2/5) * m * (r*r)}" iyz="0.0" izz="${(2/5) * m * (r*r)}"/>
    </inertial>
  </xacro:macro>

  <!-- ****************** ROBOT CONSTANTS *******************************  -->
  <!-- Define the size of the robot's main chassis in meters -->
  <xacro:property name="base_width" value="0.550"/>
  <xacro:property name="base_length" value="0.325"/>
  <xacro:property name="base_height" value="0.025"/>
  <xacro:property name="base_mass" value="0.4"/>
  <xacro:property name="quad_height" value="0.15"/>

  <!-- ****************** ROBOT BASE FOOTPRINT ***************************  -->
  <!-- Define the center of the main robot chassis projected on the ground -->	
  <link name="world"/>

  <!-- The base footprint of the robot is located underneath the chassis -->
  <joint name="base_joint" type="fixed">
    <origin xyz="0.5 0.5 0" rpy="0 0 0"/>
    <parent link="world"/>
    <child link="base_link" />
  </joint>

  <!-- ********************** ROBOT BASE *********************************  -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${quad_height}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${quad_height}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="${base_mass}" w="${base_width}" d="${base_length}" h="${base_height}">
      <origin xyz="0 0 ${quad_height}" rpy="1.57 0 1.57"/>
    </xacro:box_inertia>
  </link>

  <joint name="leg_joint" type="revolute">
    <origin xyz="${(base_length/2) + 0.005} ${(base_width/2) - 0.1} ${quad_height}" rpy="1.57 0 1.57"/>
    <parent link="base_link"/>
    <child link="leg" />
    <axis xyz="0 0 1" />
    <limit effort="10.0" lower="-1.57" upper="1.57" velocity="0.5"/>
  </joint>

  <!-- ********************** LEG *********************************  -->
  <link name="leg">
    <visual>
      <origin xyz="-0.010700 -0.086500 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find quad_description)/meshes/quad_leg.obj" scale=".001 .001 .001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="-0.010700 -0.086500 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find quad_description)/meshes/quad_leg.obj" scale=".001 .001 .001"/>
        <!-- <box size="0.04 0.065 0.2"/> -->
      </geometry>
    </collision>
    <xacro:box_inertia m="0.1" w="0.033" d="0.075" h="0.16">
      <origin xyz="0.003 -0.055 0.016" rpy="0 0 0"/>
    </xacro:box_inertia>
  </link>

  <joint name="limb_joint" type="revolute">
    <origin xyz="0 -0.1095 0" rpy="0 0 0"/>
    <parent link="leg" />
    <child link="limb" />
    <axis xyz="0 0 1" />
    <limit effort="10.0" lower="-1.57" upper="1.57" velocity="0.5"/>
    <!-- <dynamics damping="1.0" /> -->
  </joint>

  <!-- ********************** LEG *********************************  -->
  <link name="limb">
    <visual>
      <origin xyz="-0.01 0.023 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find quad_description)/meshes/quad_limb.obj" scale=".001 .001 .001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="-0.01 0.023 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find quad_description)/meshes/quad_limb.obj" scale=".001 .001 .001"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="0.08" w="0.0375" d="0.04375" h="0.13">
      <origin xyz="0.0025 -0.04 0.015" rpy="0 0 0"/>
    </xacro:box_inertia>
  </link>

</robot>
